grails.plugin.repos.discovery.grailsplugins="https://scottburch:HFQsIduda@svn.codehaus.org/grails-plugins"
user.svn.username.discovery.grailsplugins="scottburch"
user.svn.password.discovery.grailsplugins="HFQsIduda"
grails.plugin.repos.distribution.grailsplugins="https://scottburch:HFQsIduda@svn.codehaus.org/grails-plugins"
user.svn.username.distribution.grailsplugins="scottburch"
user.svn.password.distribution.grailsplugins="HFQsIduda"